### PR TITLE
Relicense to MPL-2.0

### PR DESCRIPTION
**Pull request by cwfitzgerald**
This relicenses the repository to MPL-2.0 from its current license. The following contributors need to post the following comment to approve this change. These are the only contributors who still have code attributed to them in the codebase.

- [X] @DethRaid 
- [x] @Janrupf 
- [X] @cwfitzgerald 

I approve of my code in nova-renderer being licensed under the MPL-2.0.

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
I approve of my code in nova-renderer being licensed under the MPL-2.0.

**Comment by DethRaid** [comment]
I approve of my code in nova-renderer being licensed under the MPL-2.0.

**Review by DethRaid — APPROVED** [review]

**Comment by Janrupf** [comment]
I approve of my code in nova-renderer being licensed under the MPL-2.0.

**Review by Janrupf — APPROVED** [review]

**Comment by cwfitzgerald** [comment]
Overriding because it's a non code change, and CI state is dubious on master right now.

**Comment by ghost** [comment]
So does that mean you are switching back to C++?

**Comment by cwfitzgerald** [comment]
Yes, but this issue is not the place to discuss that. Join us on the Discord.

**Pull request merged**
