### PR TITLE
Split PR CI from commit CI, so that PRs don't have to wait for eight builds

### PR DESCRIPTION
**Pull request by DethRaid**

### CODE REVIEW

**Review by cwfitzgerald — APPROVED** [review]
Grumble grumble cide duplication but I get it grumble grumble

**Comment by Janrupf** [comment]
Are you sure this works? I'm not sure that Github will not still trigger on both files.

**Comment by DethRaid** [comment]
I'm not sure of anything. This seemed like an alright way to do what I want but we'd have to merge it to properly test... Thanks GitHub

**Review by Janrupf — APPROVED** [review]
Looks good

**Pull request merged**
