### PR TITLE
Added Linux patch options

### PR DESCRIPTION
**Pull request by sayomaki**
Support 'applyPatch' for linux using 'patch' command

### CODE REVIEW

**Comment by tobiasschulz** [comment]
For windows there is ${project.projectDir} in both paths. For linux the relative paths are just hardcoded. Are you sure that works?

**Review by tobiasschulz — CHANGES_REQUESTED** [review]
add ${project.projectDir} for linux

**Review by tobiasschulz — CHANGES_REQUESTED** [review]
Add ${project.projectDir} for linux

**Comment by sayomaki** [comment]
Well technically it was using relative paths in nova.sh also, which is the current install script

**Review by tobiasschulz — APPROVED** [review]

**Pull request merged**
