### PR TITLE
Now we copy java files!

### PR DESCRIPTION
**Pull request by ckissane**

### CODE REVIEW

**Review by DethRaid — CHANGES_REQUESTED** [review]
You're copying the files into src/main/Java/mcp... You realize that all the Java code looks for the Minecraft files in src/main/Java/net though, right? That Minecraft code has to end up in that directory eventually

Did you even test this?

**Comment by ckissane** [comment]
I did test

**Comment by ckissane** [comment]
Only errors now arise from patch not being applied (mc compiles fine, Nova hooks don't)

**Comment by DethRaid** [comment]
Wasn't the whole point of this to make the patch file apply properly?

**Review by DethRaid — CHANGES_REQUESTED** [review]
We need this code. You can't just comment it out, it's integral to having Minecraft's lighting work

**Comment by ckissane** [comment]
I put the code back...
The patch works,
The code doesn't compile though.

**Comment by ckissane** [comment]
K it builds and runs now

**Review by DethRaid — APPROVED** [review]

**Pull request merged**
